### ISSUE TITLE
PORT 80 is not available but cannot change through .env.local

### ISSUE THREAD

**Issue by limyoona900530** [SoraWebui/SoraWebui#16]
Your Work is awesome! 
But my port 80 is equipped by other service and I want to change it to other.
I tried to modify the .env.local file as below but is doesn't work. ( Am I modifying the wrong one ? T-T)
![image](https://github.com/SoraWebui/SoraWebui/assets/82750867/b926eed2-f647-4123-af44-4465f31cf9a1)
Could anyone tell me how to figure this? Thanks a lot!

**Comment by lazyatwell** [comment]
u can custom the param as u want in package.json in the root path
![image](https://github.com/SoraWebui/SoraWebui/assets/150679887/39577c54-e4c6-4132-88bf-f068575cd16a)

**Comment by limyoona900530** [comment]
ohh! that works, thank you so much😘
