### ISSUE TITLE
Failed to start server

### ISSUE THREAD

**Issue by lovelydjj** [SoraWebui/SoraWebui#20]
yarn run v1.22.21
$ next dev --port 80
 ⨯ Failed to start server
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)

all l try 
input： sudo netstat -ap | grep 80
ouput：no port 80 work

**Comment by littletry** [comment]
Update two repository, set SoraWebui and FakeSoraAPI in different port. This is my WeChat ID ： LittleTryTT
