### ISSUE TITLE
【登录时候失败啦 大佬 ！！】

### ISSUE THREAD

**Issue by pengxinseo** [SoraWebui/SoraWebui#26]
Try signing in with a different account.  ！！

**Comment by pengxinseo** [comment]
![111](https://github.com/SoraWebui/SoraWebui/assets/37148931/2abdde65-b0df-4743-9ebe-e80c82667da0)

**Comment by littletry** [comment]
本地开发时候，代理需要全局，如果全局还不行，那就是你的代理问题。

**Comment by pengxinseo** [comment]
好的&nbsp; 测试了本地的问题 ，然后线上可以 感谢大佬！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月13日(星期六) 晚上6:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SoraWebui/SoraWebui] 【登录时候失败啦 大佬 ！！】 (Issue #26)














 
本地开发时候，代理需要全局，如果全局还不行，那就是你的代理问题。
