### ISSUE TITLE
【又来请教啦大佬 登录 - cookie 缓存】

### ISSUE THREAD

**Issue by pengxinseo** [SoraWebui/SoraWebui#27]
`async function init() {
    const user_id = sessionStorage.getItem("user_id");
    if (user_id) {
      await getUserById(user_id);
    } else {
      if (status == 'authenticated') {
        await getUserByEmail(session.user.email);
      } else if (status == 'unauthenticated') {
        console.log('未验证');
        setIntervalUserData(undefined);
        // https://www.npmjs.com/package/google-one-tap
        const options = {
          client_id: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID, // required
          auto_select: false, // optional
          cancel_on_tap_outside: false, // optional
          context: 'signin', // optional
        };
        googleOneTap(options, (response) => {
          const token = response.credential;
          getUserOneTap(token);
        });
      }
    }
  }`
  
  这个地方的  这段代码 我感觉 就没执行呀  
  
` googleOneTap(options, (response) => {
          const token = response.credential;
Cookies.set("iuu_userInfo", 1111, { expires: 7 }); 
          getUserOneTap(token);
        });`
        
        然后我 添加了   没结果 ，sessionStorage，也是没结果  ，然后 第一次授权成功后的 函数是哪一个呀  ，我想 set一个cookie键值对 ，这样不用每个  页面 都去数据库请求用户的信息了 ，

**Comment by pengxinseo** [comment]
![Uploading 11111.png…]()

**Comment by pengxinseo** [comment]
![11111](https://github.com/SoraWebui/SoraWebui/assets/37148931/113728fe-21a0-448c-a02d-aa6cc6fb07bc)

**Comment by littletry** [comment]
照你自己想法调吧，oneTap 你不想要就去掉，用户没登录时才会调用oneTap触发右上角弹出谷歌登录的一键登录

**Comment by pengxinseo** [comment]
明白啦 我说呢咋没登录 就走登录的逻辑 原来是右上角弹出来的登录感谢大佬！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月28日(星期天) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SoraWebui/SoraWebui] 【又来请教啦大佬 登录 - cookie 缓存】 (Issue #27)














 
照你自己想法调吧，oneTap 你不想要就去掉，用户没登录时才会调用oneTap触发右上角弹出谷歌登录的一键登录

**Comment by littletry** [comment]
除了 oneTao，上边的逻辑是点登录按钮触发，next-auth

**Comment by pengxinseo** [comment]
大佬 不忙了，帮忙看下呗

**Comment by littletry** [comment]
这是 APP router 不是 Pages router，自己去看 next 官网怎么获取数据的
在 page.tsx 里面有 await 那样获取数据就是后端渲染了

**Comment by littletry** [comment]
> 大佬 不忙了，帮忙看下呗

加个微信？不怎么看 github 消息。这是我的微信号： DevShot
