### ISSUE TITLE
Well, I tried the website and it was stupid

### ISSUE THREAD

**Issue by Exholips** [SoraWebui/SoraWebui#7]
Prompt: A luxury residential recording studio

Output:Prompt: A stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about.

**Comment by qiayue** [comment]
Thank you for trying out SoraWebui and providing your feedback. 
Currently, SoraWebui utilizes a demonstration API named FakeSoraAPI, which is not the official Sora API released by OpenAI. 
Therefore, the current version is primarily intended for demonstration purposes and may not be fully functional, particularly in generating videos from text. 
I would like to inform you that once OpenAI officially releases the Sora API, our project, SoraWebui, will promptly support and integrate it. 
We are committed to continuously updating and improving SoraWebui to provide a more advanced and comprehensive experience to users as soon as new features are rolled out by OpenAI. 
Please look forward to our future updates and improvements. Thank you for your patience and support!

**Comment by thistehneisen** [comment]
Then why do you have the Google authentication functioning already? Seems like aggregation of data for no apparent reason.

**Comment by mencomao** [comment]
stupid！

**Comment by llagerlof** [comment]
> Well, I tried the website and it was stupid

That site is total bullshit.
